#' Return all multidiffabundance tools or a selection on an mda object.
#'
#' @param D An mda object generated by \code{\link{mda.create}}.
#' @param alpha if an alpha diversity test is to be performed. Defaults to false.
#' @param beta if a beta diversity test is to be performed. Defaults to false.
#' @param group if a grouped analysis is to be performed. Defaults to false.
#' @param group.cols column names of the group values to be analyzed. Required if group is true.
#' @param continuous if a continuous value analysis is to be performed. Defaults to false.
#' @param continuous.cols column names of the continuous values to be analyzed. Required if continuous is true.
#' @param continuous.scale if the continuous values should be scaled. Defaults to true.
#' @param aldex2 if the aldex2 mda pipeline is to be performed. Defaults to true.
#' @param ancombc if the ancombc mda pipeline is to be performed. Defaults to true.
#' @param corncob if the corncob mda pipeline is to be performed. Defaults to false, due to long runtime of the analysis.
#' @param deseq2 if the deseq2 mda pipeline is to be performed. Defaults to true.
#' @param limma if the limma mda pipeline is to be performed. Defaults to true.
#' @param lmclr if the lmclr mda pipeline is to be performed. Defaults to true.
#' @param maaslin2 if the maaslin2 mda pipeline is to be performed. Defaults to true.
#' @param zicoseq if the zicoseq mda pipeline is to be performed. Defaults to true.
#'
#' @export
mda.all <- function(mda.D, alpha=FALSE, beta=FALSE, group=FALSE, continuous=FALSE,
                    aldex2=TRUE, ancombc2=TRUE, corncob=FALSE, deseq2=TRUE,
                    limma=TRUE, lmclr=TRUE, maaslin2=TRUE, zicoseq=TRUE, ...){
    suppressPackageStartupMessages(require(dplyr))
    D <- mda.D
    
    functions <- c(mda.alpha, mda.beta, mda.group, mda.continuous, mda.aldex2, mda.ancombc2, mda.corncob, mda.deseq2, mda.limma, mda.lmclr, mda.maaslin2, mda.zicoseq)
    selected <-  c(    alpha,     beta,     group,     continuous,     aldex2,     ancombc2,      corncob,     deseq2,     limma,     lmclr,     maaslin2,     zicoseq)
    
    R <- lapply(functions[selected], function(x){ x(D, ...) })
    comb <- mda.merge_results(R)
    
    return(comb)

}